### ISSUE TITLE
Implementing set_sandbox_mode from ccxt

### ISSUE THREAD

**Issue by dt2555** [Dave-Vallance/bt-ccxt-store#11]
Hello,
Thank you for working on this library. However, I would like to be able to use the set_sandbox_mode(params) from ccxt with the CCXTStore to easily interact with test nets. I have tried implementing it myself, but I am having trouble doing so. 

I get this error:

return cls.BrokerCls(*args, **kwargs)

TypeError: 'NoneType' object is not callable

**Comment by Dave-Vallance** [comment]
Hi @dt2555 

Thanks for the feature suggestion. I will add it as an enhancement request.

**Comment by maxbortone** [comment]
Hi all, I was able to get this working and tested it with the Bitmex testnet. I've added a `sandbox` paramenter to the `CCXTStore` object, which if set to `True` will call `exchange.set_sandbox_mode(True)` during initialization of the exchange. If the exchange does not support sandbox mode (like Binance), but the parameter is set to `True`, a `NotSupported` exception will be raised.

**Comment by Dave-Vallance** [comment]
Closed
