### ISSUE TITLE
How to realize hourly calculation, but also minute tracking, is it through compression?

### ISSUE THREAD

**Issue by goushijie** [Dave-Vallance/bt-ccxt-store#14]
I set compression = 60, which can only be executed once an hour. I want to execute every minute, but the data is also computed in an hour's way.
If data = store. GetData (data name ='ETH / USD', name = "eth_usd_min"),
Timeframe = BT. TimeFrame. Minutes, fromdate = hist_start_date,
Drop_newest = True, history = False, compression = 1)
Cerebro. resample data (data, timeframe = BT. TimeFrame. Minutes, compression = 60, name ='2M'), the close data calculated is incorrect. Why? Can help me

![image](https://user-images.githubusercontent.com/7100718/56459935-9c1b6f80-63cd-11e9-91e5-b4ec258465ec.png)

**Comment by Dave-Vallance** [comment]
Closing for house keeping - More of a general backtrader question

**Comment by AminSaqi** [comment]
> Closing for house keeping - More of a general backtrader question

This is NOT a backtrader related question. 

In backtrader you can simply replay data and the backtest goes well. But in live feeds through this library, the explained problem exists.
