### ISSUE TITLE
How to set the instrument to the OKEX Contracts?

### ISSUE THREAD

**Issue by helldragonx** [Dave-Vallance/bt-ccxt-store#15]
OKEX Contracts has the contracts with additional parameters, suck like: base_coin='eth', quote_coin='usd', and contractType = 'quarter', but how to set such instrument into data?
Could you give a simple sample, thanks.

**Comment by helldragonx** [comment]
Also OKEX Contracts position calling has different entry, not same with coin-coin calling.

**Comment by Dave-Vallance** [comment]
Hi @helldragonx 

To be honest, I have not tested at all on OKEX. Each exchange does have its own quirks. It might require looking into the store source code to see if these parameters can be passed.

Does OKEX have a testnet / paper trading account?

**Comment by Dave-Vallance** [comment]
Closing as no response in a long time
