### ISSUE TITLE
self.live_data is not accessible.

### ISSUE THREAD

**Issue by helldragonx** [Dave-Vallance/bt-ccxt-store#16]
AttributeError: 'Lines_LineSeries_LineIterator_DataAccessor_Strateg' object has no attribute 'live_data'

So how can I know it's historical or live data?

**Comment by Dave-Vallance** [comment]
Hi @helldragonx 
  Can you please provide a full code example (without anything proprietary in it) that can be used to recreate the issue you are seeing. 

Please remember to remove your API keys etc...

**Comment by Dave-Vallance** [comment]
closing as there has been no response in a long time
