### ISSUE TITLE
Broker feed stuck with compression

### ISSUE THREAD

**Issue by rodrigo-brito** [Dave-Vallance/bt-ccxt-store#8]
I am using the bitfinex. The exchange returns a feed of one minute. My bot uses a time-frame of 30 minutes, but it stuck with a compression different of 1.

Code:
```python
hist_start_date = dt.datetime.utcnow() - dt.timedelta(minutes=50)
data = store.getdata(dataname='BTC/USDT', name="BTCUSDT",
	timeframe=bt.TimeFrame.Minutes, fromdate=hist_start_date,
	compression=30, ohlcv_limit=999, drop_newest=True)
```

I also tried to use `cerebro.resampledata(data, timeframe=bt.TimeFrame.Minutes, compression=30)` with compression 1 in store. But does not work too.

With compression=1, the feed works fine. And next() function is triggered.

**Comment by rodrigo-brito** [comment]
I'm linux user, I'm using now the default terminal.
I activate the debug and notice that the request is sent but the feed not trigger next() function. I also discovered that a hist_start_date value, fix it, with a timedelta of 2000 minutes, works fine. This is very strange.

The full code is:
```python
broker_config = {
	'apiKey': config.get("api").get("key"),
	'secret': config.get("api").get("secret"),
	'nonce': lambda: str(int(time.time() * 1000)),
	'enableRateLimit': True,
}

store = CCXTStore(exchange='binance', currency='USDT', config=broker_config,
	retries=5, debug=True)

broker_mapping = {
	'order_types': {
		bt.Order.Market: 'market',
		bt.Order.Limit: 'limit',
		bt.Order.Stop: 'stop-loss',
		bt.Order.StopLimit: 'stop limit'
	},
	'mappings': {
		'closed_order': {
			'key': 'status',
			'value': 'closed'
		},
		'canceled_order': {
			'key': 'result',
			'value': 1
		}
	}
}

broker = store.getbroker(broker_mapping=broker_mapping)
cerebro.setbroker(broker)

hist_start_date = dt.datetime.utcnow() - dt.timedelta(minutes=50)
data = store.getdata(dataname='BTC/USDT', name="BTCUSDT",
	timeframe=bt.TimeFrame.Minutes, fromdate=hist_start_date,
	compression=30, ohlcv_limit=9999, drop_newest=True)

cerebro.adddata(data)
```

**Comment by Dave-Vallance** [comment]
@rodrigo-brito 

Can you send a full sample please? - I.e Including the strategy. If this is sensitive, please replicate it with a simple strategy that just prints something basic on the call of `next()`

I want to make sure I am using the exact same code that you see an issue with.

**Comment by rodrigo-brito** [comment]
Hi @Dave-Vallance,
A simplified version, with the reproduced issue is in the follow link: https://gist.github.com/rodrigo-brito/3b0fca2487c92ad97869247edd5fd852
Notice that  `dt.timedelta(minutes=2000)` is 2000. If you change it to 30 for example, it stop to work.

**Comment by sandroboehme** [comment]
Hi @rodrigo-brito,

I tried to reproduce your problem with your gist but without success. It works for me.
I changed your code slightly but that shouldn't have had an effect: https://gist.github.com/sandroboehme/1815de278498245f9fa046138e1767f2
It works for me with a 2000 min delta as well as with a 30 min start delta.

**Comment by Dave-Vallance** [comment]
Hi @rodrigo-brito 

Did you try @sandroboehme's gist? Is that working for you too?

**Comment by rodrigo-brito** [comment]
Hi @Dave-Vallance  and @sandroboehme, thank you for the support. I'm suspecting that it is related to my base strategy. The initial time is multiplied by the minimum time window required. I will try the gist later, maybe tomorrow, and report it back to you.

**Comment by Dave-Vallance** [comment]
Hi @rodrigo-brito

Ok - No rush! 

I was just wondering whether to keep it open or close the issue. 

Cheers

**Comment by rodrigo-brito** [comment]
Sorry for the delay, i tested you code with differente time frames and work very well. I don't now what is happening with my code. Maybe a specific indicator or other component is interfering on it.

**Comment by NekSfyris** [comment]
Hello, in regards to this issue, I can also verify that your code indeed returns data after 30 min. However, when comparing the candle's low, high, close, and open with the same candle's attributes in Tradingview or Binance they don't match. And if the candle is not the same of course an indicator will return false results too.

Is the code too outdated?

> Hi @rodrigo-brito,
> 
> I tried to reproduce your problem with your gist but without success. It works for me. I changed your code slightly but that shouldn't have had an effect: https://gist.github.com/sandroboehme/1815de278498245f9fa046138e1767f2 It works for me with a 2000 min delta as well as with a 30 min start delta.
